# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtUser',
            fields=[
                ('student_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='\u5b66\u53f7')),
                ('xclass', models.CharField(default='', max_length=100, verbose_name='\u73ed\u7ea7')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ext', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
