# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_extuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_ok', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6210\u529f')),
                ('ext_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='backend.ExtUser')),
            ],
        ),
    ]
